Repository Droggol/VscOdooSnippets, pull requests merged in 2019-06, with the labels that each got.

#7 [IMP] add metadata badges in README
  README.md
Labels: enhancement

#9 [IMP] better changelog typos
  CHANGELOG.md
Labels: enhancement :+1:

#10 Fix oodefine indentation and semicolon
  snippets/js_snippets.json
Labels: bug

#11 Fix ooscript tag
  snippets/xml_snippets.json
Labels: bug

#12 [IMP] add missing docs for snippets
  DOCUMENTATION.md
Labels: enhancement :+1:

#13 [ADD] added new snippets for xml
  DOCUMENTATION.md
  snippets/xml_snippets.json
Labels: enhancement :+1:
